######################################################################
# VoidSeeker Bot Development Compose for Docker on Windows
######################################################################

version: '3.2'
services:
  voidseeker:
    build: ../
    restart: always
    container_name: VoidSeeker

    external_links:
      - voidseeker-db:db
    depends_on:
      - voidseeker-db
    volumes:
      - c:\voidseeker\log:/opt/voidseekerLog
      - c:\voidseeker\data:/opt/voidseekerStore
    environment:
      ALEMBIC_BASE: libvoidseeker.model.base
      DISCORD_BOT_SECRET: NA
      DISCORD_OWNING_USER_ID: NA
      DATABASE_URL: postgresql+psycopg://botUser:botPass@db:5432/voidseeker
    networks:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "3"

  voidseeker-db:
    image: postgres:16.2-alpine3.19
    restart: always
    security_opt:
      - seccomp=unconfined
    ports:
      - 5433:5432
    volumes:
      - c:\voidseeker\dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: botPass
      POSTGRES_DB: botDb
      POSTGRES_USER: botUser
      PGDATA: /var/lib/postgresql/data/pgdata
#    you should remove the DB from the frontend network in production if the host is internet facing
    networks:
      backend:
      frontend:

networks:
  frontend:
    internal: false
  backend:
    internal: true