"""empty message

Revision ID: 14f1966b7a67
Revises: 
Create Date: 2025-10-28 17:31:20.736578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f1966b7a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.BigInteger(), nullable=True),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.Column('userName', sa.Unicode(length=64), nullable=True),
    sa.Column('addedAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authUsers_id'), 'authUsers', ['id'], unique=False)
    op.create_index(op.f('ix_authUsers_serverId'), 'authUsers', ['serverId'], unique=False)
    op.create_table('banActions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.BigInteger(), nullable=True),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.Column('bannedAt', sa.DateTime(), nullable=True),
    sa.Column('userName', sa.Unicode(length=64), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('joinedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banActions_id'), 'banActions', ['id'], unique=False)
    op.create_index(op.f('ix_banActions_serverId'), 'banActions', ['serverId'], unique=False)
    op.create_table('banTerms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.BigInteger(), nullable=True),
    sa.Column('term', sa.Unicode(length=256), nullable=True),
    sa.Column('termType', sa.String(length=256), nullable=True),
    sa.Column('addedByUserId', sa.BigInteger(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banTerms_id'), 'banTerms', ['id'], unique=False)
    op.create_index(op.f('ix_banTerms_serverId'), 'banTerms', ['serverId'], unique=False)
    op.create_table('honeyPotChannels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.BigInteger(), nullable=True),
    sa.Column('messageId', sa.BigInteger(), nullable=True),
    sa.Column('channelId', sa.BigInteger(), nullable=True),
    sa.Column('banCount', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honeyPotChannels_id'), 'honeyPotChannels', ['id'], unique=False)
    op.create_index(op.f('ix_honeyPotChannels_serverId'), 'honeyPotChannels', ['serverId'], unique=False)
    op.create_table('immuneRoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.BigInteger(), nullable=True),
    sa.Column('roleId', sa.BigInteger(), nullable=True),
    sa.Column('addedByUserId', sa.BigInteger(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immuneRoles_id'), 'immuneRoles', ['id'], unique=False)
    op.create_index(op.f('ix_immuneRoles_serverId'), 'immuneRoles', ['serverId'], unique=False)
    op.create_table('serverSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.BigInteger(), nullable=True),
    sa.Column('honeyPotEnabled', sa.Boolean(), nullable=True),
    sa.Column('honeyPotText', sa.UnicodeText(), nullable=True),
    sa.Column('heuristicsEnabled', sa.Boolean(), nullable=True),
    sa.Column('banOnPingAll', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serverSettings_id'), 'serverSettings', ['id'], unique=False)
    op.create_index(op.f('ix_serverSettings_serverId'), 'serverSettings', ['serverId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serverSettings_serverId'), table_name='serverSettings')
    op.drop_index(op.f('ix_serverSettings_id'), table_name='serverSettings')
    op.drop_table('serverSettings')
    op.drop_index(op.f('ix_immuneRoles_serverId'), table_name='immuneRoles')
    op.drop_index(op.f('ix_immuneRoles_id'), table_name='immuneRoles')
    op.drop_table('immuneRoles')
    op.drop_index(op.f('ix_honeyPotChannels_serverId'), table_name='honeyPotChannels')
    op.drop_index(op.f('ix_honeyPotChannels_id'), table_name='honeyPotChannels')
    op.drop_table('honeyPotChannels')
    op.drop_index(op.f('ix_banTerms_serverId'), table_name='banTerms')
    op.drop_index(op.f('ix_banTerms_id'), table_name='banTerms')
    op.drop_table('banTerms')
    op.drop_index(op.f('ix_banActions_serverId'), table_name='banActions')
    op.drop_index(op.f('ix_banActions_id'), table_name='banActions')
    op.drop_table('banActions')
    op.drop_index(op.f('ix_authUsers_serverId'), table_name='authUsers')
    op.drop_index(op.f('ix_authUsers_id'), table_name='authUsers')
    op.drop_table('authUsers')
    # ### end Alembic commands ###
