"""empty message

Revision ID: 3fb3d607da9f
Revises: 478c7673fa17
Create Date: 2026-03-27 22:48:00.309838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb3d607da9f'
down_revision = '478c7673fa17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocrRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.BigInteger(), nullable=True),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.Column('requestJson', sa.JSON(), nullable=True),
    sa.Column('addedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocrRequests_id'), 'ocrRequests', ['id'], unique=False)
    op.create_index(op.f('ix_ocrRequests_serverId'), 'ocrRequests', ['serverId'], unique=False)
    op.create_table('ocrResults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.BigInteger(), nullable=True),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.Column('addedAt', sa.DateTime(), nullable=True),
    sa.Column('ocrResultJson', sa.JSON(), nullable=True),
    sa.Column('historic', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocrResults_id'), 'ocrResults', ['id'], unique=False)
    op.create_index(op.f('ix_ocrResults_serverId'), 'ocrResults', ['serverId'], unique=False)
    op.add_column('banActions', sa.Column('ocrResultId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'banActions', 'ocrResults', ['ocrResultId'], ['id'])
    op.add_column('serverSettings', sa.Column('ocrRules', sa.JSON(), nullable=True))
    op.add_column('serverSettings', sa.Column('ocrEnabled', sa.Boolean(), nullable=True))
    op.add_column('serverSettings', sa.Column('ocrImageCount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serverSettings', 'ocrImageCount')
    op.drop_column('serverSettings', 'ocrEnabled')
    op.drop_column('serverSettings', 'ocrRules')
    op.drop_constraint(None, 'banActions', type_='foreignkey')
    op.drop_column('banActions', 'ocrResultId')
    op.drop_index(op.f('ix_ocrResults_serverId'), table_name='ocrResults')
    op.drop_index(op.f('ix_ocrResults_id'), table_name='ocrResults')
    op.drop_table('ocrResults')
    op.drop_index(op.f('ix_ocrRequests_serverId'), table_name='ocrRequests')
    op.drop_index(op.f('ix_ocrRequests_id'), table_name='ocrRequests')
    op.drop_table('ocrRequests')
    # ### end Alembic commands ###
