"""empty message

Revision ID: 478c7673fa17
Revises: 61dbd7a16f62
Create Date: 2025-11-02 13:15:05.576965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478c7673fa17'
down_revision = '61dbd7a16f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banActions', sa.Column('banId', sa.Integer(), nullable=True))
    op.add_column('serverSettings', sa.Column('heuristicsBanText', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serverSettings', 'heuristicsBanText')
    op.drop_column('banActions', 'banId')
    # ### end Alembic commands ###
