"""empty message

Revision ID: 61dbd7a16f62
Revises: 14f1966b7a67
Create Date: 2025-10-31 20:41:01.886477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61dbd7a16f62'
down_revision = '14f1966b7a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banActions', sa.Column('detectionMethod', sa.String(length=64), nullable=True))
    op.drop_column('honeyPotChannels', 'banCount')
    op.add_column('serverSettings', sa.Column('banCount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serverSettings', 'banCount')
    op.add_column('honeyPotChannels', sa.Column('banCount', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('banActions', 'detectionMethod')
    # ### end Alembic commands ###
