"""empty message

Revision ID: af93c606e007
Revises: 3fb3d607da9f
Create Date: 2026-04-01 14:56:05.474019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af93c606e007'
down_revision = '3fb3d607da9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocrResults', sa.Column('rulesBreached', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocrResults', 'rulesBreached')
    # ### end Alembic commands ###
