"""empty message

Revision ID: b1382ae02cd9
Revises: d0f5a069b570
Create Date: 2026-06-11 21:30:12.916108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1382ae02cd9'
down_revision = 'd0f5a069b570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serverSettings', sa.Column('welcomeCheckEnabled', sa.Boolean(), nullable=True))
    op.add_column('serverSettings', sa.Column('welcomeCheckChannelId', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serverSettings', 'welcomeCheckChannelId')
    op.drop_column('serverSettings', 'welcomeCheckEnabled')
    # ### end Alembic commands ###
