"""empty message

Revision ID: d0f5a069b570
Revises: af93c606e007
Create Date: 2026-04-01 19:40:40.961744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f5a069b570'
down_revision = 'af93c606e007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocrRequests', sa.Column('channelId', sa.BigInteger(), nullable=True))
    op.add_column('ocrResults', sa.Column('channelId', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocrResults', 'channelId')
    op.drop_column('ocrRequests', 'channelId')
    # ### end Alembic commands ###
